/**
 * MysticEast AI - I Ching (Yijing) Divination Engine
 *
 * 64 Hexagrams database with names, meanings, and line texts.
 */

export interface Hexagram {
  number: number;
  name: string;
  nameEn: string;
  symbol: string; // e.g., "䷀"
  judgment: string;
  image: string;
  lines: string[]; // 6 lines, from bottom (line 1) to top (line 6)
}

// Line types
export type LineType = 'old-yin' | 'young-yang' | 'young-yin' | 'old-yang';

// 64卦完整数据库
export const HEXAGRAMS: Hexagram[] = [
  { number: 1, name: '乾', nameEn: 'The Creative', symbol: '䷀', judgment: 'The Creative works sublime success, furthering through perseverance.', image: 'The movement of heaven is full of power. Thus the superior man makes himself strong and untiring.', lines: ['Hidden dragon. Do not act.','Dragon appearing in the field. It furthers one to see the great man.','All day long the superior man is creatively active. At nightfall his mind is still beset with cares. Danger. No blame.','Wavering flight over the depths. No blame.','Flying dragon in the heavens. It furthers one to see the great man.','Arrogant dragon will have cause to repent.'] },
  { number: 2, name: '坤', nameEn: 'The Receptive', symbol: '䷁', judgment: 'The Receptive brings about sublime success, furthering through the perseverance of a mare.', image: 'The earth\'s condition is receptive devotion. Thus the superior man who has breadth of character carries the outer world.', lines: ['When there is hoarfrost underfoot, solid ice is not far off.','Straight, square, great. Without purpose, yet nothing remains unfurthered.','Hidden lines. One is able to remain persevering. If by chance you are in the service of a king, seek not works, but bring to completion.','A tied-up sack. No blame, no praise.','A yellow lower garment brings supreme good fortune.','Dragons fight in the meadow. Their blood is black and yellow.'] },
  { number: 3, name: '屯', nameEn: 'Difficulty at the Beginning', symbol: '䷂', judgment: 'Difficulty at the Beginning works supreme success, furthering through perseverance.', image: 'Clouds and thunder: The image of Difficulty at the Beginning. Thus the superior man brings order out of confusion.', lines: ['Hesitation and hindrance. It furthers one to remain persevering. To appoint helpers.','Difficulties pile up. Horse and wagon part. He is not a robber; He wants to woo when the time comes.','Whoever hunts deer without a forester only loses his way in the forest.','Horse and wagon part. Seek union.','Difficulty at the beginning brings supreme success.','Horse and wagon part. Bloody tears flow.'] },
  { number: 4, name: '蒙', nameEn: 'Youthful Folly', symbol: '䷃', judgment: 'Youthful Folly has success. It is not I who seek the young fool; The young fool seeks me.', image: 'A spring wells up at the foot of the mountain: The image of Youth. Thus the superior man fosters his character by thoroughness in all that he does.', lines: ['To make a fool develop It furthers one to apply discipline.','To bear with fools in kindliness brings good fortune.','Take not a maiden who, when she sees a man of bronze, loses possession of herself.','Entangled folly brings humiliation.','Childlike folly brings good fortune.','In punishing folly, it does not further one to commit transgressions.'] },
  { number: 5, name: '需', nameEn: 'Waiting (Nourishment)', symbol: '䷄', judgment: 'Waiting. If you are sincere, you have light and success.', image: 'Clouds rise up to heaven: The image of Waiting. Thus the superior man eats and drinks, is joyous and of good cheer.', lines: ['Waiting in the meadow. It furthers one to abide in what endures.','Waiting on the sand. There is some gossip.','Waiting in the mud brings about the arrival of the enemy.','Waiting in blood. Get out of the pit.','Waiting at meat and drink. Perseverance brings good fortune.','One falls into the pit. Three uninvited guests arrive.'] },
  { number: 6, name: '讼', nameEn: 'Conflict', symbol: '䷅', judgment: 'Conflict. You are sincere And are being obstructed. A cautious halt halfway brings good fortune.', image: 'Heaven and water go their opposite ways: The image of Conflict. Thus in all his transactions the superior man carefully considers the beginning.', lines: ['If one does not perpetuate the affair, There is a little gossip.','One cannot engage in conflict; One returns home, gives way.','To nourish oneself on ancient virtue induces perseverance.','One cannot engage in conflict. One turns back and submits to fate.','To contend before him brings supreme good fortune.','Even if by chance a leather belt is bestowed on one, by the end of a morning it will have been snatched away three times.'] },
  { number: 7, name: '师', nameEn: 'The Army', symbol: '䷆', judgment: 'The Army. The army needs perseverance And a strong man. Good fortune without blame.', image: 'In the middle of the earth is water: The image of the Army. Thus the superior man increases his masses by generosity toward the people.', lines: ['An army must set forth in proper order. If the order is not good, misfortune threatens.','In the midst of the army. Good fortune. No blame.','Perchance the army carries corpses in the wagon. Misfortune.','The army retreats. No blame.','There is game in the field. It furthers one to catch it.','The great prince issues commands, Founds states, vests families with fiefs.'] },
  { number: 8, name: '比', nameEn: 'Holding Together', symbol: '䷇', judgment: 'Holding Together brings good fortune. Inquire of the oracle once again Whether you possess sublimity, constancy, and perseverance;', image: 'On the earth is water: The image of Holding Together. Thus the kings of antiquity Bestowed the different states as fiefs and cultivated friendly relations with the feudal lords.', lines: ['Hold to him in truth and loyalty; This is without blame.','Hold to him inwardly. Perseverance brings good fortune.','You hold together with the wrong people.','Hold to him outwardly also. Perseverance brings good fortune.','Manifestation of holding together. In the hunt the king uses beaters on three sides only.','He finds no head for holding together. Misfortune.'] },
  { number: 9, name: '小畜', nameEn: 'The Taming Power of the Small', symbol: '䷈', judgment: 'The Taming Power of the Small Has success. Dense clouds, no rain from our western region.', image: 'The wind drives across heaven: The image of the Taming Power of the Small. Thus the superior man refines the outward aspect of his nature.', lines: ['Return to the way. How could there be blame in this? Good fortune.','He allows himself to be drawn into returning. Good fortune.','The spokes burst out of the wagon wheels. Man and wife roll their eyes.','If you are sincere, blood vanishes and fear gives way. No blame.','If you are sincere and loyally attached, You are rich in your neighbor.','The rain comes, there is rest.'] },
  { number: 10, name: '履', nameEn: 'Treading (Conduct)', symbol: '䷉', judgment: 'Treading. Treading upon the tail of the tiger. It does not bite the man. Success.', image: 'Heaven above, the lake below: The image of Treading. Thus the superior man discriminates between high and low, And thereby fortifies the thinking of the people.', lines: ['Simple conduct. Progress without blame.','Treading a smooth, level course. The perseverance of a dark man Brings good fortune.','A one-eyed man is able to see, A lame man is able to tread.','Treading on the tail of the tiger. Caution.','Treading with determination. Danger.','Look to your conduct and weigh the favorable signs.'] },
  { number: 11, name: '泰', nameEn: 'Peace', symbol: '䷊', judgment: 'Peace. The small departs, The great approaches. Good fortune. Success.', image: 'Heaven and earth unite: the image of Peace. Thus the ruler Divides and completes the course of heaven and earth; He furthers and regulates the gifts of heaven and earth, And so aids the people.', lines: ['When ribbon grass is pulled up, the sod comes with it.','Bearing with the uncultured in gentleness, Fording the river with resolution,','No plain not followed by a slope. No going not followed by a return.','He flutters down, not boasting of his wealth.','The sovereign gives his daughter in marriage.','The wall falls back into the moat. Use no army now.'] },
  { number: 12, name: '否', nameEn: 'Standstill (Stagnation)', symbol: '䷋', judgment: 'Standstill. Evil people do not further The perseverance of the superior man. The great departs; the small approaches.', image: 'Heaven and earth do not unite: The image of Standstill. Thus the superior man falls back upon his inner worth In order to escape the difficulties.', lines: ['When ribbon grass is pulled up, the sod comes with it.','They bear and endure; This means good fortune for inferior people.','They bear shame.','He who acts at the command of the highest Remains without blame.','Standstill is giving way. Good fortune for the great man.','The standstill comes to an end.'] },
  { number: 13, name: '同人', nameEn: 'Fellowship with Men', symbol: '䷌', judgment: 'Fellowship with Men in the open. Success. It furthers one to cross the great water.', image: 'Heaven together with fire: The image of Fellowship with Men. Thus the superior man organizes the clans And makes distinctions between things.', lines: ['Fellowship with men at the gate. No blame.','Fellowship with men in the clan. Humiliation.','He hides weapons in the thicket; He climbs the high hill in front of it.','He climbs up on his wall; he cannot attack.','Men bound in fellowship first weep and lament, But afterward they laugh.','Fellowship with men in the meadow. No remorse.'] },
  { number: 14, name: '大有', nameEn: 'Possession in Great Measure', symbol: '䷍', judgment: 'Possession in Great Measure. Supreme success.', image: 'Fire in heaven above: the image of Possession in Great Measure. Thus the superior man curbs evil and furthers good, And thereby obeys the benevolent will of heaven.', lines: ['No relationship with what is harmful; There is no blame in this.','A big wagon for loading.','A prince offers it to the Son of Heaven.','He makes a difference Between himself and his neighbor.','His sincerity is manifest.','He is blessed by heaven. Good fortune.'] },
  { number: 15, name: '谦', nameEn: 'Modesty', symbol: '䷎', judgment: 'Modesty creates success. The superior man carries things through.', image: 'Within the earth, a mountain: The image of Modesty. Thus the superior man reduces that which is too much, And augments that which is too little.', lines: ['A superior man modest about his modesty may cross the great water. Good fortune.','Modesty that comes to expression. Perseverance brings good fortune.','A superior man of modesty and merit carries things to conclusion.','Nothing that would not further modesty In movement.','Not rich in your neighbor: Be enriched by your modesty.','Modesty that comes to expression. It is favorable to set armies marching.'] },
  { number: 16, name: '豫', nameEn: 'Enthusiasm', symbol: '䷏', judgment: 'Enthusiasm. It furthers one to install helpers And to set armies marching.', image: 'Thunder comes resounding out of the earth: The image of Enthusiasm. Thus the ancient kings made music In order to honor merit, And offered it with splendor to the Supreme Deity, Inviting their ancestors to be present.', lines: ['Enthusiasm that expresses itself Brings misfortune.','Firm as a rock. Not a whole day. Perseverance brings good fortune.','Enthusiasm that looks upward creates remorse.','The source of enthusiasm. He achieves great things.','Illness of the skin. Never dying, never reviving.','Enthusiasm that is dark. Perseverance brings misfortune.'] },
  { number: 17, name: '随', nameEn: 'Following', symbol: '䷐', judgment: 'Following has supreme success. Perseverance furthers. No blame.', image: 'Thunder in the middle of the lake: The image of Following. Thus the superior man at nightfall Goes indoors for rest and recuperation.', lines: ['The standard is changing. Perseverance brings good fortune.','If one clings to the little boy, One loses the strong man.','If one clings to the strong man, One loses the little boy.','Following creates success. Perseverance brings misfortune.','Sincere in the good. Good fortune.','He meets with firm allegiance And is still further bound.'] },
  { number: 18, name: '蛊', nameEn: 'Work on What Has Been Spoiled', symbol: '䷑', judgment: 'Work on What Has Been Spoiled Has supreme success. It furthers one to cross the great water.', image: 'The wind blows low on the mountain: The image of Decay. Thus the superior man stirs up the people And strengthens their spirit.', lines: ['Setting right what has been spoiled by the father.','Setting right what has been spoiled by the mother.','Setting right what has been spoiled by the father. There is a little regret, but no great blame.','Tolerating what has been spoiled by the father.','Setting right what has been spoiled by the father. One meets with praise.','He does not serve kings and princes, Sets himself higher goals.'] },
  { number: 19, name: '临', nameEn: 'Approach', symbol: '䷒', judgment: 'Approach has supreme success. Perseverance furthers. When the eighth month comes, There will be misfortune.', image: 'The earth above the lake: The image of Approach. Thus the superior man is inexhaustible In his will to teach, And without limits In his tolerance and protection of the people.', lines: ['Joint approach. Perseverance brings good fortune.','Joint approach. Good fortune.','Comfortable approach. Nothing that would further.','Complete approach. No blame.','Wise approach. This is right for a great prince.','Great hearted approach. Good fortune. No blame.'] },
  { number: 20, name: '观', nameEn: 'Contemplation (View)', symbol: '䷓', judgment: 'Contemplation. The ablution has been made, but not yet the offering. Full of trust they look up to him.', image: 'The wind blows over the earth: The image of Contemplation. Thus the kings of old visited the regions of the world, Contemplated the ways of the people, And gave them instruction.', lines: ['Boylike contemplation. For an inferior man, no blame.','Contemplation through the crack of the door.','Contemplation of my life Decides the choice Between advance and retreat.','Contemplation of the light of the kingdom.','Contemplation of my life. The superior man is without blame.','Contemplation of his life. The superior man is without blame.'] },
  { number: 21, name: '噬嗑', nameEn: 'Biting Through', symbol: '䷔', judgment: 'Biting Through has success. It is favorable to let justice be administered.', image: 'Thunder and lightning: The image of Biting Through. Thus the kings of former times made firm the laws Through clearly defined penalties.', lines: ['His feet are fastened in the stocks, His toes are hurt.','One bites through tender meat.','One bites on dried meat and breaks a metal tooth.','One bites on dried gristly meat.','One bites on dried lean meat.','His neck is fastened in the wooden cangue, So that his ears disappear.'] },
  { number: 22, name: '贲', nameEn: 'Grace', symbol: '䷕', judgment: 'Grace has success. In small matters It is favorable to undertake something.', image: 'Fire at the foot of the mountain: The image of Grace. Thus does the superior man proceed When clearing up current affairs.', lines: ['He lends grace to his toes, leaves the carriage and walks.','Lends grace to the beard on his chin.','Graceful and moist. Constant perseverance brings good fortune.','Grace or simplicity? A white horse comes as if on wings.','Grace in hills and gardens.','Too simple grace. No blame.'] },
  { number: 23, name: '剥', nameEn: 'Splitting Apart', symbol: '䷖', judgment: 'Splitting Apart. It does not further one To go anywhere.', image: 'The mountain rests on the earth: The image of Splitting Apart. Thus those above can ensure their position Only by giving generously to those below.', lines: ['The leg of the bed is split. Those who persevere are destroyed.','The bed is split at the edge.','He splits with them. No blame.','The bed is split up to the skin.','A shoal of fishes. The primer minister communicates it to the prince.','The wild goose gradually draws near the cloud heights.'] },
  { number: 24, name: '复', nameEn: 'Return (The Turning Point)', symbol: '䷗', judgment: 'Return. Success. Going out and coming in without harm. Friends come without blame.', image: 'Thunder within the earth: The image of the Turning Point. Thus the kings of antiquity closed the passes At the time of solstice.', lines: ['Return from a short distance. No need for remorse. Great good fortune.','Quiet return. Good fortune.','Repeated return. Danger. No blame.','Walking in the midst of others, One returns alone.','Noblehearted return. No remorse.','Missing the return. Misfortune.'] },
  { number: 25, name: '无妄', nameEn: 'Innocence (The Unexpected)', symbol: '䷘', judgment: 'Innocence. Supreme success. Perseverance furthers. If someone is not as he should be, He has misfortune, And it does not further him To undertake anything.', image: 'Under heaven thunder rolls: All things attain the natural state of innocence. Thus the kings of old, Rich in virtue, and in harmony with the time, Fostered and nourished all beings.', lines: ['Innocent behavior brings good fortune.','If one does not count on the harvest while plowing, Nor on the use of the ground while clearing it, It furthers one to undertake something.','Undeserved misfortune.','He who can be persevering Remains without blame.','Use no medicine in an illness Incurred through no fault of your own.','Innocent action brings misfortune.'] },
  { number: 26, name: '大畜', nameEn: 'The Taming Power of the Great', symbol: '䷙', judgment: 'The Taming Power of the Great. Perseverance furthers. Not eating at home brings good fortune.', image: 'Heaven within the mountain: The image of the Taming Power of the Great. Thus the superior man acquaints himself with many sayings of antiquity And many deeds of the past, In order to strengthen his character thereby.', lines: ['Danger is at hand. It furthers one to desist.','The carriage is disconnected at the axle.','A good horse that follows others.','The headboard of a young bull. Great good fortune.','The tusk of a gelded boar. Good fortune.','One attains the way of heaven. Success.'] },
  { number: 27, name: '颐', nameEn: 'The Corners of the Mouth (Providing Nourishment)', symbol: '䷚', judgment: 'The Corners of the Mouth. Perseverance brings good fortune. Pay heed to the providing of nourishment.', image: 'At the foot of the mountain, thunder: The image of Providing Nourishment. Thus the superior man is careful of his words And temperate in eating and drinking.', lines: ['You let your magic tortoise go, And look at me with the corners of your mouth drooping.','Turning to the summit for nourishment, Deviating from the path.','Turning away from nourishment. Perseverance brings misfortune.','Turning to the summit For provision of nourishment Brings good fortune.','Turning away from the path. To remain persevering brings good fortune.','The source of nourishment.'] },
  { number: 28, name: '大过', nameEn: 'Preponderance of the Great', symbol: '䷛', judgment: 'Preponderance of the Great. The ridgepole sags to the breaking point. It furthers one to have somewhere to go.', image: 'The lake rises above the trees: The image of Preponderance of the Great. Thus the superior man, when he stands alone, Is unconcerned, And if he has to renounce the world, He is undaunted.', lines: ['To spread white rushes underneath. No blame.','A dry poplar sprouts at the root.','The ridgepole sags to the breaking point.','The ridgepole is braced. Good fortune.','A withered poplar puts forth flowers.','One must go through the water.'] },
  { number: 29, name: '坎', nameEn: 'The Abysmal (Water)', symbol: '䷜', judgment: 'The Abysmal repeated. If you are sincere, you have success in your heart, And whatever you do succeeds.', image: 'Water flows on uninterruptedly and reaches its goal: The image of the Abysmal repeated. Thus the superior man walks in lasting virtue And carries on the business of teaching.', lines: ['In the abyss one falls into a pit. Misfortune.','The abyss is dangerous.','Forward and backward, abyss on abyss.','A jug of wine, a bowl of rice with it.','The abyss is not filled to overflowing,','Bound with cords and ropes, Shut in between thorn-hedged prison walls.'] },
  { number: 30, name: '离', nameEn: 'The Clinging, Fire', symbol: '䷝', judgment: 'The Clinging. Perseverance furthers. It brings success. Care of the cow brings good fortune.', image: 'That which is bright rises twice: The image of Fire. Thus the great man, by perpetuating this brightness, Illumines the four quarters of the world.', lines: ['The footprints run crisscross. If one is seriously intent, no blame.','Yellow light. Supreme good fortune.','In the light of the setting sun, Men either beat the pot and sing Or loudly bewail the approach of old age.','Its coming is sudden; It flames up, dies down, is thrown away.','Tears in floods, sighing and lamenting.','The king uses him to march forth and chastise.'] },
  { number: 31, name: '咸', nameEn: 'Influence (Wooing)', symbol: '䷞', judgment: 'Influence. Success. Perseverance furthers. To take a maiden to wife brings good fortune.', image: 'A lake on the mountain: The image of Influence. Thus the superior man encourages people to approach him By his readiness to receive them.', lines: ['The influence shows itself in the big toe.','The influence shows itself in the calves of the legs.','The influence shows itself in the thighs.','Perseverance brings good fortune. Remorse disappears.','The influence shows itself in the back of the neck.','The influence shows itself in the jaws, cheeks, and tongue.'] },
  { number: 32, name: '恒', nameEn: 'Duration', symbol: '䷟', judgment: 'Duration. Success. No blame. Perseverance furthers. It furthers one to have somewhere to go.', image: 'Thunder and wind: the image of Duration. Thus the superior man stands firm And does not change his direction.', lines: ['Seeking duration too hastily brings misfortune persistently.','Remorse disappears.','He who does not give duration to his character Meets with disgrace.','No game in the field.','Giving duration to one\'s character through perseverance.','The wild goose gradually draws near the cloud heights.'] },
  { number: 33, name: '遁', nameEn: 'Retreat', symbol: '䷠', judgment: 'Retreat. Success. In what is small, perseverance furthers.', image: 'Mountain under heaven: the image of Retreat. Thus the superior man keeps the inferior man at a distance, Not angrily but with reserve.', lines: ['At the tail in retreat. This is dangerous.','He holds him fast with yellow oxhide. No one can tear him loose.','A halted retreat Is nerve-wracking and dangerous.','Voluntary retreat brings good fortune to the superior man.','Friendly retreat. Perseverance brings good fortune.','Cheerful retreat. Everything serves to further.'] },
  { number: 34, name: '大壮', nameEn: 'The Power of the Great', symbol: '䷡', judgment: 'The Power of the Great. Perseverance furthers.', image: 'Thunder in heaven above: The image of the Power of the Great. Thus the superior man does not tread upon paths That do not accord with established order.', lines: ['Power in the toes. Continuing brings misfortune.','Perseverance brings good fortune.','The inferior man works through power. The superior man does not act thus.','The hedge opens; there is no entanglement.','Loses the goat with ease.','The goat butts against a hedge.'] },
  { number: 35, name: '晋', nameEn: 'Progress', symbol: '䷢', judgment: 'Progress. The powerful prince Is honored with horses in large numbers. In a single day he is granted audience three times.', image: 'The sun rises over the earth: The image of Progress. Thus the superior man himself Brightens his bright virtue.', lines: ['Progressing, but turned back.','Progressing, but in sorrow.','All are in accord. Remorse disappears.','Progress like a hamster.','Remorse disappears. Take not gain and loss to heart.','Progressing with the horns is permissible Only for the purpose of punishing one\'s own city.'] },
  { number: 36, name: '明夷', nameEn: 'Darkening of the Light', symbol: '䷣', judgment: 'Darkening of the Light. In adversity It furthers one to be persevering.', image: 'The light has sunk into the earth: The image of Darkening of the Light. Thus does the superior man live with the great mass: He veils his light, yet still shines.', lines: ['Darkening of the light during flight.','Darkening of the light injures him in the left thigh.','Darkening of the light during the hunt in the south.','He penetrates the left side of the belly.','Darkening of the light as with Prince Chi.','Not light but darkness.'] },
  { number: 37, name: '家人', nameEn: 'The Family (The Clan)', symbol: '䷤', judgment: 'The Family. The perseverance of the woman furthers.', image: 'Wind comes forth from fire: The image of the Family. Thus the superior man has substance in his words And duration in his way of life.', lines: ['He establishes a household through firmness.','She should not follow her whims.','When tempers flare up in the family, Too great severity brings remorse.','She is the treasure of the house.','As a king he approaches his family.','His work commands respect.'] },
  { number: 38, name: '睽', nameEn: 'Opposition', symbol: '䷥', judgment: 'Opposition. In small matters, good fortune.', image: 'Above, fire; below, the lake: The image of Opposition. Thus amid all fellowship The superior man retains his individuality.', lines: ['Remorse disappears. If you lose your horse, do not run after it;','One meets his lord in a narrow street. No blame.','One sees the wagon dragged back,','Isolated through opposition. One meets a like-minded man.','Remorse disappears. The companion bites his way through the wrappings.','Isolated through opposition. One sees his companion as his pig covered with dirt,'] },
  { number: 39, name: '蹇', nameEn: 'Obstruction', symbol: '䷦', judgment: 'Obstruction. The southwest furthers. The northeast does not further.', image: 'Water on the mountain: The image of Obstruction. Thus the superior man turns his attention to himself And molds his character.', lines: ['Going leads to obstructions, Coming meets with praise.','The king\'s servant is beset by obstruction upon obstruction,','Going leads to obstructions; Hence he comes back.','Going leads to obstructions, Coming leads to union.','In the midst of the greatest obstructions, Friends come.','Going leads to obstructions, Coming leads to great good fortune.'] },
  { number: 40, name: '解', nameEn: 'Deliverance', symbol: '䷧', judgment: 'Deliverance. The southwest furthers. If there is no longer anything where one has to go, Return brings good fortune.', image: 'Thunder and rain set in: The image of Deliverance. Thus the superior man pardons mistakes And forgives misdeeds.', lines: ['Without blame.','One kills three foxes in the field And receives a yellow arrow.','If a man carries a burden on his back And nonetheless rides in a carriage,','Remove your toes. Friends will then come, no doubt about it.','If only the superior man can deliver himself, It brings good fortune.','The prince shoots at a hawk on a high wall.'] },
  { number: 41, name: '损', nameEn: 'Decrease', symbol: '䷨', judgment: 'Decrease combined with sincerity Brings about supreme good fortune Without blame.', image: 'At the foot of the mountain, the lake: The image of Decrease. Thus the superior man controls his anger And restrains his instincts.', lines: ['Going quickly when one\'s tasks are finished Is without blame.','Perseverance furthers. To undertake something brings misfortune.','When three people journey together, Their number decreases by one.','If a man decreases his faults, It makes the other hasten to come and rejoice.','Someone does indeed increase him.','He gives increase to others without decrease to himself.'] },
  { number: 42, name: '益', nameEn: 'Increase', symbol: '䷩', judgment: 'Increase. It furthers one To undertake something. It furthers one to cross the great water.', image: 'Wind and thunder: the image of Increase. Thus the superior man: If he sees good, he imitates it; If he has faults, he rids himself of them.', lines: ['It furthers one to accomplish great deeds.','Someone does indeed increase him;','One is enriched through unfortunate events.','If you walk in the middle And report to the prince, He will follow.','If in truth you have a kind heart, ask not.','He brings increase to no one.'] },
  { number: 43, name: '夬', nameEn: 'Break-through (Resoluteness)', symbol: '䷪', judgment: 'Break-through. One must resolutely make the matter known At the court of the king.', image: 'The lake has risen up to heaven: The image of Break-through. Thus the superior man Dispenses riches downward And refrains from resting on his virtue.', lines: ['Mighty in the forward-striding toes.','A cry of alarm. Arms at evening and at night.','To be powerful in the cheekbones Brings misfortune.','There is no skin on his thighs, And walking comes hard.','In dealing with weeds, Firm resolution is necessary.','No cry. In the end misfortune comes.'] },
  { number: 44, name: '姤', nameEn: 'Coming to Meet', symbol: '䷫', judgment: 'Coming to Meet. The maiden is powerful. One should not marry such a maiden.', image: 'Under heaven, wind: The image of Coming to Meet. Thus does the prince act when disseminating his commands And proclaiming them to the four quarters of heaven.', lines: ['It must be checked with a brake of bronze.','There is a fish in the tank. No blame.','There is no skin on his thighs, And walking comes hard.','No fish in the tank. This leads to misfortune.','A melon covered with willow leaves.','He comes to meet with his horns.'] },
  { number: 45, name: '萃', nameEn: 'Gathering Together (Massing)', symbol: '䷬', judgment: 'Gathering Together. Success. The king approaches his temple. It furthers one to see the great man.', image: 'Over the earth, the lake: The image of Gathering Together. Thus the superior man renews his weapons In order to meet the unforeseen.', lines: ['If you are sincere, but not to the end, There will sometimes be confusion, sometimes gathering together.','Letting oneself be drawn Brings good fortune and remains blameless.','Gathering together amid sighs.','Great good fortune. No blame.','If in gathering together one has position, This is no blame.','Lamenting and sighing, floods of tears.'] },
  { number: 46, name: '升', nameEn: 'Pushing Upward', symbol: '䷭', judgment: 'Pushing Upward has supreme success. One must see the great man, Fear not.', image: 'Within the earth, wood grows: The image of Pushing Upward. Thus the superior man of devoted character Heaps up small things In order to achieve something high and great.', lines: ['Pushing upward that meets with confidence Brings great good fortune.','If one is sincere, It furthers one to bring even a small offering.','One pushes upward into an empty city.','The king offers him Mount Ch\'i.','Perseverance brings good fortune.','Pushing upward in darkness.'] },
  { number: 47, name: '困', nameEn: 'Oppression (Exhaustion)', symbol: '䷮', judgment: 'Oppression. Success. Perseverance. The great man brings about good fortune.', image: 'There is no water in the lake: The image of Exhaustion. Thus the superior man stakes his life On following his will.', lines: ['One sits oppressed under a bare tree And strays into the gloom.','One is oppressed while at meat and drink.','A man permits himself to be oppressed by stone.','He comes very quietly, oppressed in a golden carriage.','His nose and feet are cut off.','He is oppressed by creeping vines.'] },
  { number: 48, name: '井', nameEn: 'The Well', symbol: '䷯', judgment: 'The Well. The town may be changed, But the well cannot be changed.', image: 'Water over wood: The image of the Well. Thus the superior man encourages the people at their work, And exhorts them to help one another.', lines: ['One does not drink the mud of the well. No blame.','At the wellhole one shoots fishes.','The well is cleaned, but no one drinks from it.','The well is being lined. No blame.','In the well there is a clear, cold spring From which one can drink.','One draws from the well Without hindrance.'] },
  { number: 49, name: '革', nameEn: 'Revolution (Molting)', symbol: '䷰', judgment: 'Revolution. On your own day You are believed. Supreme success, Furthering through perseverance. Remorse disappears.', image: 'Fire in the lake: the image of Revolution. Thus the superior man Sets the calendar in order And makes the seasons clear.', lines: ['He is bound with yellow oxhide.','When one\'s own day comes, one may create revolution.','Starting brings misfortune. Perseverance brings danger.','Remorse disappears. Men believe him.','The great man changes like a tiger.','The superior man changes like a panther.'] },
  { number: 50, name: '鼎', nameEn: 'The Caldron', symbol: '䷱', judgment: 'The Caldron. Supreme good fortune. Success.', image: 'Fire over wood: The image of the Caldron. Thus the superior man consolidates his fate By making his position correct.', lines: ['A ting with legs upturned.','There is food in the ting.','The handle of the ting is altered.','The legs of the ting are broken.','The ting has yellow handles, golden carrying rings.','The ting has rings of jade.'] },
  { number: 51, name: '震', nameEn: 'The Arousing (Shock, Thunder)', symbol: '䷲', judgment: 'Shock brings success. Shock comes—oh, oh! Laughing words—ha, ha!', image: 'Thunder repeated: the image of Shock. Thus in fear and trembling The superior man sets his life in order And examines himself.', lines: ['Shock comes—oh, oh! Then follow laughing words—ha, ha!','Shock comes bringing danger.','Shock comes and makes one distraught.','Shock is mired.','Shock goes hither and thither.','Shock brings ruin and terrified gazing around.'] },
  { number: 52, name: '艮', nameEn: 'Keeping Still, Mountain', symbol: '䷳', judgment: 'Keeping Still. Keeping his back still So that he no longer feels his body. He goes into his courtyard And does not see his people. No blame.', image: 'Mountains standing close together: The image of Keeping Still. Thus the superior man Does not permit his thoughts To go beyond his situation.', lines: ['Keeping his toes still. No blame.','Keeping his calves still.','Keeping his hips still.','Keeping his trunk still.','Keeping his jaws still.','Noblehearted keeping still.'] },
  { number: 53, name: '渐', nameEn: 'Development (Gradual Progress)', symbol: '䷴', judgment: 'Development. The maiden Is given in marriage. Good fortune. Perseverance furthers.', image: 'On the mountain, a tree: The image of Development. Thus the superior man abides in dignity and virtue, In order to improve the mores.', lines: ['The wild goose gradually draws near the shore.','The wild goose gradually draws near the cliff.','The wild goose gradually draws near the plateau.','The wild goose gradually draws near the tree.','The wild goose gradually draws near the summit.','The wild goose gradually draws near the cloud heights.'] },
  { number: 54, name: '归妹', nameEn: 'The Marrying Maiden', symbol: '䷵', judgment: 'The Marrying Maiden. Undertakings bring misfortune. Nothing that would further.', image: 'Thunder over the lake: The image of the Marrying Maiden. Thus the superior man Understands the transitory In the light of the eternity of the end.', lines: ['The marrying maiden as a concubine.','A one-eyed man who is able to see.','The marrying maiden as a slave.','The marrying maiden draws out the allotted time.','The emperor I gives his daughter in marriage.','The woman holds the basket, but there are no fruits in it.'] },
  { number: 55, name: '丰', nameEn: 'Abundance (Fullness)', symbol: '䷶', judgment: 'Abundance has success. The king attains abundance. Be not sad. Be like the sun at midday.', image: 'Both thunder and lightning come: The image of Abundance. Thus the superior man decides lawsuits And carries out punishments.', lines: ['When a man meets his destined ruler, They can be together ten days,','The curtain is of such fullness That the polestars can be seen at noon.','The small are abundant, the great are departed.','The curtain is of such fullness That the polestars can be seen at noon.','Lines are coming blessing and fame draw near.','His house is in a state of abundance.'] },
  { number: 56, name: '旅', nameEn: 'The Wanderer', symbol: '䷷', judgment: 'The Wanderer. Success through smallness. Perseverance brings good fortune To the wanderer.', image: 'Fire on the mountain: The image of the Wanderer. Thus the superior man Is clear-minded and cautious In imposing penalties, And protracts no lawsuits.', lines: ['If the wanderer busies himself with trivial things, He draws down misfortune upon himself.','The wanderer comes to an inn.','The wanderer\'s inn burns down.','The wanderer rests in a shelter.','He shoots a pheasant. It drops with the first arrow.','The bird\'s nest burns up.'] },
  { number: 57, name: '巽', nameEn: 'The Gentle (The Penetrating, Wind)', symbol: '䷸', judgment: 'The Gentle. Success through what is small. It furthers one to have somewhere to go. It furthers one to see the great man.', image: 'Winds following one upon the other: The image of the Gently Penetrating. Thus the superior man Spreads his commands abroad And carries out his undertakings.', lines: ['In advancing and in retreating, The perseverance of a warrior furthers.','Penetration under the bed.','Repeated penetration. Humiliation.','Remorse vanishes. During the hunt Three kinds of game are caught.','Perseverance brings good fortune.','Penetration under the bed.'] },
  { number: 58, name: '兑', nameEn: 'The Joyous, Lake', symbol: '䷹', judgment: 'The Joyous. Success. Perseverance is favorable.', image: 'Lakes resting one on the other: The image of the Joyous. Thus the superior man joins with his friends For discussion and practice.', lines: ['Contented joyousness. Good fortune.','Sincere joyousness. Good fortune.','Coming joyousness. Misfortune.','Joyousness that is weighed is not at peace.','Sincerity toward disintegrating influences is dangerous.','Seductive joyousness.'] },
  { number: 59, name: '涣', nameEn: 'Dispersion (Dissolution)', symbol: '䷺', judgment: 'Dispersion. Success. The king approaches his temple. It furthers one to cross the great water.', image: 'The wind drives over the water: The image of Dispersion. Thus the kings of old sacrificed to the Lord And built temples.', lines: ['He brings help with the strength of a horse.','At the dissolution He hurries to that which supports him.','He dissolves his self.','He dissolves the bond with his group.','His loud cries are as dissolving as sweat.','He dissolves his blood.'] },
  { number: 60, name: '节', nameEn: 'Limitation', symbol: '䷻', judgment: 'Limitation. Success. Galling limitation must not be persevered in.', image: 'Water over lake: the image of Limitation. Thus the superior man Creates number and measure, And examines the nature of virtue and correct conduct.', lines: ['Not going out of the door and the courtyard Is without blame.','Not going out of the gate and the courtyard brings misfortune.','He who knows no limitation Will have cause to lament.','Contented limitation. Success.','Sweet limitation brings good fortune.','Galling limitation.'] },
  { number: 61, name: '中孚', nameEn: 'Inner Truth', symbol: '䷼', judgment: 'Inner Truth. Pigs and fishes. Good fortune. It furthers one to cross the great water.', image: 'Wind over lake: the image of Inner Truth. Thus the superior man discusses criminal cases In order to delay executions.', lines: ['Being prepared brings good fortune.','A crane calling in the shade.','He finds a comrade.','The moon nearly at the full. The team horse goes astray.','He possesses truth, which links together.','Chanticleer\'s voice mounts to heaven.'] },
  { number: 62, name: '小过', nameEn: 'Preponderance of the Small', symbol: '䷽', judgment: 'Preponderance of the Small. Success. Perseverance furthers. Small things may be done; great things should not be done.', image: 'Thunder on the mountain: The image of Preponderance of the Small. Thus in his conduct the superior man gives preponderance to reverence.', lines: ['The bird meets with misfortune through flying.','She passes by her ancestor And meets her ancestress.','If one is not extremely careful, Somebody may come up from behind and strike him.','No blame. He meets him without passing by.','Dense clouds, no rain from our western region.','He passes him by, not meeting him.'] },
  { number: 63, name: '既济', nameEn: 'After Completion', symbol: '䷾', judgment: 'After Completion. Success in small matters. Perseverance furthers. At the beginning good fortune, At the end disorder.', image: 'Water over fire: the image of the condition In After Completion. Thus the superior man Takes thought of misfortune And arms himself against it in advance.', lines: ['He brakes his wheels.','The woman loses the curtain of her carriage.','The Illustrious Ancestor Disciplines the Devil\'s Country.','The finest clothes turn to rags.','The neighbor in the east who slaughters an ox Does not attain as much real happiness As the neighbor in the west With his small offering.','He gets his head in the water. Danger.'] },
  { number: 64, name: '未济', nameEn: 'Before Completion', symbol: '䷿', judgment: 'Before Completion. Success. But if the little fox, after nearly completing the crossing, Gets his tail in the water, There is nothing that would further.', image: 'Fire over water: The image of the condition before transition. Thus the superior man is careful In the differentiation of things, So that each finds its place.', lines: ['He gets his tail in the water.','He brakes his wheels.','Before completion, attack brings misfortune.','Perseverance brings good fortune.','Perseverance brings good fortune. No blame.','Getting his head in the water. Danger.'] },
];

/**
 * 投掷铜钱获取一个爻
 * 3枚铜钱，每枚有正反两面：
 * - 2正1反 = 少阴 (---) 不变
 * - 2反1正 = 少阳 (- -) 不变
 * - 3正 = 老阳 (- - -> ---) 变爻
 * - 3反 = 老阴 (--- -> - -) 变爻
 */
export function castLine(): { type: LineType; value: number; changing: boolean } {
  // 模拟3枚铜钱投掷 (0=反面，1=正面)
  const coins = [Math.random() > 0.5 ? 1 : 0, Math.random() > 0.5 ? 1 : 0, Math.random() > 0.5 ? 1 : 0];
  const heads = coins.filter(c => c === 1).length; // 正面数量
  
  if (heads === 3) {
    // 三正 = 老阳，变爻，阳爻(1)变阴爻(0)
    return { type: 'old-yang', value: 1, changing: true };
  } else if (heads === 0) {
    // 三反 = 老阴，变爻，阴爻(0)变阳爻(1)
    return { type: 'old-yin', value: 0, changing: true };
  } else if (heads === 2) {
    // 两正一反 = 少阴，不变，阴爻
    return { type: 'young-yin', value: 0, changing: false };
  } else {
    // 两反一正 = 少阳，不变，阳爻
    return { type: 'young-yang', value: 1, changing: false };
  }
}

/**
 * 投掷6次获取完整卦象
 */
export function castHexagram(): {
  lines: { type: LineType; value: number; changing: boolean }[];
  mainHexagram: number;
  changedHexagram: number;
  changingLines: number[];
} {
  const lines: { type: LineType; value: number; changing: boolean }[] = [];
  
  // 投掷6次，从下到上
  for (let i = 0; i < 6; i++) {
    lines.push(castLine());
  }
  
  // 主卦（原始卦象）
  const mainBinary = lines.map(l => l.value).join('');
  const mainHexagram = binaryToHexagram(mainBinary);
  
  // 变卦（变爻后的卦象）
  const changedBinary = lines.map(l => l.changing ? (l.value === 1 ? 0 : 1) : l.value).join('');
  const changedHexagram = binaryToHexagram(changedBinary);
  
  // 变爻位置（从1开始计数，从下到上）
  const changingLines = lines
    .map((l, i) => l.changing ? i + 1 : 0)
    .filter(i => i > 0);
  
  return { lines, mainHexagram, changedHexagram, changingLines };
}

/**
 * 二进制转卦象编号
 * 阴爻=0, 阳爻=1，从下到上
 */
function binaryToHexagram(binary: string): number {
  const map: Record<string, number> = {
    '000000': 2, '000001': 23, '000010': 8, '000011': 20, '000100': 16, '000101': 35,
    '000110': 45, '000111': 12, '001000': 15, '001001': 52, '001010': 39, '001011': 53,
    '001100': 62, '001101': 56, '001110': 31, '001111': 33, '010000': 7, '010001': 4,
    '010010': 29, '010011': 59, '010100': 40, '010101': 64, '010110': 47, '010111': 6,
    '011000': 46, '011001': 18, '011010': 48, '011011': 57, '011100': 32, '011101': 50,
    '011110': 28, '011111': 44, '100000': 24, '100001': 27, '100010': 3, '100011': 42,
    '100100': 51, '100101': 21, '100110': 17, '100111': 25, '101000': 36, '101001': 22,
    '101010': 63, '101011': 37, '101100': 55, '101101': 30, '101110': 49, '101111': 13,
    '110000': 10, '110001': 54, '110010': 60, '110011': 41, '110100': 19, '110101': 61,
    '110110': 38, '110111': 58, '111000': 11, '111001': 26, '111010': 5, '111011': 9,
    '111100': 34, '111101': 14, '111110': 43, '111111': 1,
  };
  return map[binary] || 1;
}

/**
 * 获取卦象信息
 */
export function getHexagram(number: number): Hexagram | undefined {
  return HEXAGRAMS.find(h => h.number === number);
}

/**
 * 获取爻辞
 */
export function getLineText(hexagram: Hexagram, lineNumber: number): string {
  if (lineNumber >= 1 && lineNumber <= 6) {
    return hexagram.lines[lineNumber - 1];
  }
  return '';
}

/**
 * 生成占卜结果
 */
export function generateDivination(): {
  mainHexagram: Hexagram;
  changedHexagram: Hexagram;
  changingLines: number[];
  lineTexts: string[];
} {
  const cast = castHexagram();
  const main = getHexagram(cast.mainHexagram)!;
  const changed = getHexagram(cast.changedHexagram)!;
  
  const lineTexts = cast.changingLines.map(lineNum => getLineText(main, lineNum));
  
  return {
    mainHexagram: main,
    changedHexagram: changed,
    changingLines: cast.changingLines,
    lineTexts,
  };
}
